config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
  end

  resources :categories, only: :show

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name

  has_many :restaurants, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  belongs_to :category, optional: true
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments

  def admin?
    self.role == "admin"
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin

  private

    def authenticate_admin
      unless current_user.admin?
        flash[:alert] = "Not allow!"
        redirect_to root_path
      end
    end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:update, :destroy]

  def index 
    @categories = Category.all

    if params[:id]
      set_category
    else
      @category = Category.new
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category was successfully created"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path
      flash[:notice] = "category was successfully updated"
    else
      @categories = Category.all
      render :index
    end
  end

  def destroy
    @category.destroy
    flash[:alert] = "category was successfully deleted"
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  before_action :set_restaurane, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end
  
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "restaurant was successfully updated"
      redirect_to admin_restaurant_path(@restaurant)
    else
      flash.now[:alert] = "restaurant was failed to update"
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "restaurant was deleted"
  end
  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end  

  def set_restaurane
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end
  
  def show
  @restaurant = Restaurant.find(params[:id])
  @comment = Comment.new
  end

  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/categories/index.html.erb
<div class="container">

  <h1>餐廳分類總表</h1>

  <div class="row">

    <div class="col-md-12">
      <div>
        <%= link_to 'Restaurant', admin_restaurants_path %>
        <%= link_to 'Categories', admin_categories_path %>
      </div>
      <br>
      <div class="form-inline" >
        <%= form_for [:admin, @category] do |f| %>
        <div class="form-group">
          <%= f.text_field :name, placeholder: "Category Name",  class: "form-control" %>
        </div>
        <%= f.submit class: "btn btn-primary" %>
          <% if @category.errors.any? %>
            <%= @category.errors.full_messages.to_sentence %>
          <% end %>
        <% end %>
      </div>


      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Category Name</th>
            <th>#</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <th scope="row"><%= category.id %></th>
            <td><%= category.name %></td>
            <td>
              <%= link_to 'Edit', admin_categories_path(id: category.id) %>
              <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>

app/views/admin/restaurants/_form.html.erb
<div class="container">
  <% if @restaurant.errors.any? %>
   <h2>We have some errors here !</h2>
   <ul>
     <% @restaurant.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
   </ul>
  <% end %>

  <%= form_for  [:admin, @restaurant] do |f| %>
  
  <div class="form-group">
    <%= f.label :category, "Category" %>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :tel, "Tel" %>
    <%= f.text_field :tel, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address, "Address" %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :opening_hours, "Opening Hours" %>
    <%= f.text_field :opening_hours, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image, "Photo" %>
    <%= image_tag @restaurant.image, width: '300px' if @restaurant.image? %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<div class="container">

  <h1>餐廳後台</h1>

  <div class="row">

    <div class="col-md-12">
    
      <div>
        <%= link_to 'Restaurant', admin_restaurants_path %>
        <%= link_to 'Categories', admin_categories_path %>
      </div>

      <div>
        <%= link_to 'New Restaurant', new_admin_restaurant_path, class: "btn btn-primary" %>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Category</th>
            <th>Name</th>
            <th>#</th>
          </tr>
        </thead>
        <tbody>
          <% @restaurants.each do |restaurant| %>
          <tr>
            <th scope="row"><%= restaurant.id %></th>
            <td><%= restaurant.category.name %></td>
            <td><%= restaurant.name %></td>
            <td>
              <%= link_to 'Show', admin_restaurant_path(restaurant) %>
              <%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %>
              <%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: {confirm:"Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="text-center">
        <%= paginate @restaurants %>
      </div>
    </div>
  </div>
</div>

app/views/admin/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for  [:admin, @restaurant] do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :opening_hours, "Opening Hours" %>
  <%= f.text_field :opening_hours %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/admin/restaurants/show.html.erb
<div class="container">
  <div class="well well-sm">
    <h1><%= @restaurant.name %></h1>
    <%= @restaurant.category.name %>
  </div>
  <div class="well">
    <%= image_tag @restaurant.image, class: "img-responsive center-block" %><br>
    <strong>Opening Hours:</strong><%= @restaurant.opening_hours %><br>
    <strong>Tel:</strong> <%= @restaurant.tel %><br>
    <strong>Address:</strong> <%= @restaurant.address %><br>
    <strong>Description:</strong><%= simple_format @restaurant.description %><br>
  </div>

  <div class="well well-sm">
    <%= link_to 'Back to index', admin_restaurants_path %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">

    <ul class="nav nav-pills nav-pills-center">
      <li role="presentation">
        <%= link_to "全部餐廳", root_path %>
      </li>
      <!-- 這邊判斷category==@category的時候要加 li.active -->
      <% @categories.each do |category| %>
        <li role="presentation" class="<%= "active" if category == @category %>">
          <%= link_to category.name, category_path(category) %>
        </li>
      <% end %>
    </ul>

    <br>

    <%= render partial: "shared/restaurant_list" %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
     <!--nav bar-->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <p class="navbar-text"><%= link_to('餐廳評論網', root_path) %></p>
        </div>
        <!-- Collect the nav links for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <div class="nav navbar-nav navbar-right">
            <% if current_user %> 
              <p class="navbar-text">Hi, <%= current_user.email %></p>
              <% if current_user.admin? %>
                <li><%= link_to('後台', admin_restaurants_path) %></li>
              <% end %>
              <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
              <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
            <% else %>
              <li><%= link_to('註冊', new_user_registration_path) %></li>
              <li><%= link_to('登入', new_user_session_path) %></li>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% end %>
    
    <% if flash[:alert] %>    
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <ul class="nav nav-pills nav-pills-center">
      <li role="presentation" class="active"><%= link_to "全部餐廳", root_path %></li>
      <% @categories.each do |category| %>
      <li role="presentation"><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>

    <br>

    <%= render partial: "shared/restaurant_list" %>
      
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <p>[<%= @restaurant.category.name %>]</p>
    </div>

    <div class="col-md-4">
      <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
          <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
          <li><strong>Address:</strong> <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
    </div>

    <div class="clearfix"></div>

    <hr>
    <!-- 顯示與餐廳相關的評論 -->
    <% @restaurant.comments.each do |comment| %>
    <div>
      <h4><%= comment.user.email.split("@").first %></h4>
      <p><%= simple_format comment.content %></p>
      <p class="text-muted">
        <em><%= time_ago_in_words(comment.created_at) %> ago -</em>
       <% if current_user.admin? %>
        <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete %>
      <% end %> 
      </p>
    </div>
    <hr>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
   <%= form_for [@restaurant, @comment] do |f| %>
    <div class="form-group">
      <%= f.text_area :content, placeholder: "留個言吧", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
      <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
    </div>
  <% end %>
  </div>
</div>

app/views/shared/_restaurant_list.html.erb
<!-- restaurants list，有多寫restaurant-item的class style -->
<% @restaurants.each do |restaurant| %>
  <div class="col-sm-6 col-md-4">
    <div class="restaurant-item">
      <%= image_tag restaurant.image, class: "img-responsive center-block" %>
      <div class="caption">
        <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
        <p class="label label-default"><%= restaurant.category.name %><p>
        <p><%= truncate(restaurant.description, length: 80) %></p>
      </div>
    </div>
  </div>

<% end %>

<!-- 有generate kaminari paginate bootstrap style -->
<div class="text-center">
  <%= paginate @restaurants %>
</div>